"""Generate the replay versions of the two Kaggle tasks (preregistration 098, Deviation 3).

    python scripts/build_kaggle_replay.py results/kaggle-memory-discipline-001/report.json

Why a replay exists. The live tasks (Kaggle version 2) never named their main task with
`%choose`, so for every run Kaggle ingested one per-item subtask run, which has no number, and
the benchmark leaderboard shows "-" for every model although the runs completed and their output
holds the score. Kaggle cannot re-read an old run's output, so the only ways to fill the
leaderboard are to call every model again or to replay the recorded result. This writes the
replay: a task that does NOT call the model. It carries, per model, whether each item was answered
correctly in the run that preregistration 098 scored (`report.json`, written by the frozen
analysis), recomputes the family score with `kaggle_memory/scoring.py` copied verbatim, and ends
with `%choose` so the leaderboard reads that number. The live runs stay on Kaggle as version 2.

Per item the data is `1` (correct), `0` (incorrect) or `-` (errored, so left out of every
denominator, as the analysis does). A model with no recorded run raises instead of scoring.
"""

import hashlib
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ITEMS = json.loads((REPO / "kaggle_memory" / "items.json").read_text(encoding="utf-8"))
SCORING = REPO / "kaggle_memory" / "scoring.py"
OUT = REPO / "kaggle_memory" / "tasks"
FAMILIES = {
    "trust": ("present", "superseded", "TRUST_CONDITIONS"),
    "restraint": ("absent", "adjacent", "contradictory", "RESTRAINT_CONDITIONS"),
}


def norm(slug):
    """Model identity tolerant of provider prefix and punctuation ('@' against '-')."""
    return re.sub(r"[^a-z0-9]", "", slug.lower().split("/")[-1])


def encode(report, family):
    order = [(i["item_id"], i["condition"]) for i in ITEMS if i["family"] == family]
    models = {}
    for model, entry in sorted(report.items()):
        got = {row["item_id"]: row["correct"] for row in entry["items"]}
        models[model] = "".join("-" if iid not in got else "1" if got[iid] else "0"
                                for iid, _ in order)
    keys = [norm(m) for m in models]
    assert len(set(keys)) == len(keys), "two models normalise to the same key"
    return {"items": order, "models": models}


TEMPLATE = '''# %%
# Memory discipline benchmark, {family} half: REPLAY of the preregistered runs (version 3).
#
# THIS VERSION DOES NOT CALL THE MODEL. It replays, per model, which items were answered correctly
# in the run that preregistration 098 scored, and recomputes the score with the benchmark's own
# scorer. The live runs, where each model answered all 216 items, are version 2 of this task.
# Why: version 2 did not name its main task with %choose, so Kaggle's leaderboard could not read
# its scores (Deviation 3 in preregistration/098-kaggle-memory-discipline.md).
#
# GENERATED by scripts/build_kaggle_replay.py in github.com/GiulioDER/agent-memory-bench.
# Do not edit by hand. report.json sha256: {report_sha}  scoring.py sha256: {scoring_sha}
import json
import re

import kaggle_benchmarks as kbench

# %%
# ---- kaggle_memory/scoring.py, verbatim ----
{scoring}
# ---- end of scoring.py ----

# %%
REPLAY = json.loads(r"""{data}""")


def _key(model):
    if model in REPLAY["models"]:
        return model
    norm = lambda slug: re.sub(r"[^a-z0-9]", "", slug.lower().split("/")[-1])
    hits = [m for m in REPLAY["models"] if norm(m) == norm(model)]
    if len(hits) != 1:
        raise KeyError(f"no recorded preregistered run for {{model!r}}; this replay scores only those")
    return hits[0]


def replay_results(model):
    key = _key(model)
    marks = REPLAY["models"][key]
    return key, [{{"item_id": item_id, "condition": condition, "correct": mark == "1"}}
                 for (item_id, condition), mark in zip(REPLAY["items"], marks) if mark != "-"]


@kbench.task(
    name="memory-discipline-{family}",
    description="Replay of the preregistered run (098): no model call; scores the recorded answers.",
)
def memory_discipline_{family}(llm) -> float:
    key, results = replay_results(getattr(llm, "model", None) or str(llm))
    score = family_score(results, {conditions})
    print("MEMORY_DISCIPLINE_REPLAY " + json.dumps({{
        "family": "{family}", "model": key, "scored_items": len(results),
        "errored": len(REPLAY["items"]) - len(results), "score": score,
    }}))
    return score


memory_discipline_{family}.run(kbench.llm)

# %%
# Keep only this task's task and run files, so the leaderboard reads this score.
# %choose memory_discipline_{family}
'''


def build(report_path):
    report_bytes = Path(report_path).read_bytes()
    report = json.loads(report_bytes)
    scoring = SCORING.read_text(encoding="utf-8")
    written = []
    for family, spec in FAMILIES.items():
        data = json.dumps(encode(report, family), separators=(",", ":"))
        assert '"""' not in data
        text = TEMPLATE.format(
            family=family, conditions=spec[-1], data=data, scoring=scoring.rstrip("\n"),
            report_sha=hashlib.sha256(report_bytes.replace(b"\r\n", b"\n")).hexdigest(),
            scoring_sha=hashlib.sha256(scoring.encode("utf-8")).hexdigest())
        path = OUT / f"replay_{family}.py"
        path.write_bytes(text.encode("utf-8"))
        written.append(path)
    return written


if __name__ == "__main__":
    for p in build(sys.argv[1]):
        print(p.relative_to(REPO), p.stat().st_size, "bytes")
