"""Generate the `draft` protocol variant from the standard one, changing ONE section.

Preregistration 024 tests whether searching with the code about to be written beats searching by
operation. That is a change to the shared protocol's "How to search" section and nothing else, so
this splices that one section and leaves every other byte identical. Doing it by generation rather
than by hand is what makes "one variable" checkable instead of asserted: `tests/test_draft_protocol.py`
re-runs this and refuses if the committed file differs.

Run: python -m scripts.build_draft_protocol [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SOURCE = REPO / "adapters" / "_shared" / "memory_protocol.md"
TARGET = REPO / "adapters" / "_shared" / "memory_protocol_draft.md"

OPEN = "## How to search\n"
CLOSE = "## When to do this\n"

#: The only text that differs from the standard protocol. It replaces the operation-decomposition
#: advice with draft-text advice, keeps the same length band so prompt size is not the variable,
#: and deliberately reuses the standard section's worked example so the contrast is the METHOD and
#: not the illustration.
DRAFT_SECTION = """## How to search

You cannot name a symptom you have not hit yet, and you cannot describe a hazard you do not know
exists. What you always have is **the text you are about to write**: the file contents, the edit,
the command. Search with that text itself, not with a description of what you are trying to achieve.

So the search that works is the one issued with your draft in hand, a moment before you save it:

- About to write `version_file.write_text(content, encoding="utf-8")`? Search with that line.
- About to run `alembic upgrade head` against production? Search with that command.
- About to add `requests = "^2.31"` to a manifest? Search with that fragment.

The reason this works is not subtle. A note about a failure contains the literal identifiers the
failure happened in, and so does your draft; a description of your goal contains neither. In the
recorded miss above, "version bump" appears nowhere in the note, but the note's own fix line is
`path.write_text(text, encoding="utf-8", newline="\\n")`, which shares four identifiers with the
draft that was about to be saved and none with the goal.

Short is fine and short is normal: one edit hunk or one command is a complete query. Do not
assemble a summary of your plan, and do not paste an entire file.

"""


def render() -> str:
    text = SOURCE.read_bytes().decode("utf-8")
    start = text.find(OPEN)
    end = text.find(CLOSE)
    if start < 0 or end < 0 or end <= start:
        raise SystemExit(
            f"{SOURCE.name} no longer has a '## How to search' section before '## When to do this'; "
            f"the draft variant is generated by splicing exactly that span and cannot guess a new one"
        )
    out = text[:start] + DRAFT_SECTION + text[end:]
    if out.count("{search_instruction}") != 1:
        raise SystemExit("the draft protocol must carry the search slot exactly once")
    if "abstention-sensitive" not in out:
        raise SystemExit("the draft protocol lost the abstention-sensitive block")
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not TARGET.is_file():
            print(f"{TARGET.name} is missing; run this without --check", file=sys.stderr)
            return 1
        if TARGET.read_bytes().decode("utf-8") != rendered:
            print(
                f"{TARGET.name} differs from what this script generates. Either regenerate it or "
                f"change DRAFT_SECTION; do not hand-edit the file, because then 'one variable' "
                f"stops being checkable.",
                file=sys.stderr,
            )
            return 1
        print(f"  {TARGET.name} is current")
        return 0
    # write_bytes so the bytes land exactly as rendered. Without it Python rewrites every line
    # ending on Windows, the whole file reads as changed, and the "one variable" claim this script
    # exists to make becomes uncheckable. That is the CRLF hazard the protocol's own worked example
    # is about, hit while generating the protocol.
    TARGET.write_bytes(rendered.encode("utf-8"))
    src = SOURCE.read_text(encoding="utf-8")
    same_head = len(src) - len(src[src.find(OPEN):])
    same_tail = len(src) - src.find(CLOSE)
    print(f"  wrote {TARGET.relative_to(REPO).as_posix()}  ({len(rendered)} chars)")
    print(f"  standard: {len(src)} chars   identical head {same_head} + tail {same_tail}")
    print("  the ONLY difference is the '## How to search' section")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
